export const invoices = [
  {
    id: 1,
    customer: "/images/blog/blog-img2.jpg",
    customer_name: "Popular Authors",
    handle: "Most Successful",
    tranche: "40%",
    amount: "$9000",
    status: "pending",
    product_name: "awaHealth",
    slug: "one",
    total_amount: 9983,
    grand_total: 9933,
    vat: 7.5,
    service: ["Brand Design, UI/Ux, Web dev"],
  },
  {
    id: 2,
    customer: "/images/blog/blog-img2.jpg",
    customer_name: "Popular Authors",
    handle: "Most Successful",
    tranche: "50%",
    amount: "$700",
    status: "pending",
    slug: "two",
    product_name: "PF",
    total_amount: 9983,
    grand_total: 9993,
    vat: 7.5,
    service: ["Web dev"],
  },
  {
    id: 3,
    customer: "/images/blog/blog-img2.jpg",
    customer_name: "Popular Authors",
    handle: "Most Successful",
    tranche: "60%",
    amount: "$20000",
    total_amount: 9983,
    grand_total: 99834,
    vat: 7.5,
    status: "paid",
    slug: "three",
    product_name: "Venture Nation",
    service: ["Brand Design, Web Dev"],
  },
];
