export const currencies = [
  "AED",
  "AFN",
  "ALL",
  "AMD",
  "ANG",
  "AOA",
  "ARS",
  "AUD",
  "AWG",
  "AZN",
  "BAM",
  "BBD",
  "BDT",
  "BGN",
  "BHD",
  "BIF",
  "BMD",
  "BND",
  "BOB",
  "BRL",
  "BSD",
  "BTN",
  "BWP",
  "BYN",
  "BZD",
  "CAD",
  "CDF",
  "CHF",
  "CLP",
  "CNY",
  "COP",
  "CRC",
  "CUP",
  "CVE",
  "CZK",
  "DJF",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ERN",
  "ETB",
  "EUR",
  "FJD",
  "FKP",
  "FOK",
  "GBP",
  "GEL",
  "GGP",
  "GHS",
  "GIP",
  "GMD",
  "GNF",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HRK",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "IMP",
  "INR",
  "IQD",
  "IRR",
  "ISK",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KID",
  "KMF",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "LYD",
  "MAD",
  "MDL",
  "MGA",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MRU",
  "MUR",
  "MVR",
  "MWK",
  "MXN",
  "MYR",
  "MZN",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PAB",
  "PEN",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "PYG",
  "QAR",
  "RON",
  "RSD",
  "RUB",
  "RWF",
  "SAR",
  "SBD",
  "SCR",
  "SDG",
  "SEK",
  "SGD",
  "SHP",
  "SLL",
  "SOS",
  "SRD",
  "SSP",
  "STN",
  "SYP",
  "SZL",
  "THB",
  "TJS",
  "TMT",
  "TND",
  "TOP",
  "TRY",
  "TTD",
  "TVD",
  "TWD",
  "TZS",
  "UAH",
  "UGX",
  "USD",
  "UYU",
  "UZS",
  "VES",
  "VND",
  "VUV",
  "WST",
  "XAF",
  "XCD",
  "XOF",
  "XPF",
  "YER",
  "ZAR",
  "ZMW",
  "ZWL",
];

export const currenciesWithCountries = [
  { country: "Nigeria", currency: "NGN" },
  // { country: "United States", currency: "USD" },
];

export const countriesWithNationality = [
  { country: "United Arab Emirates", nationality: "Emirati" },
  { country: "Afghanistan", nationality: "Afghan" },
  { country: "Albania", nationality: "Albanian" },
  { country: "Armenia", nationality: "Armenian" },
  { country: "Netherlands Antilles", nationality: "Dutch Antillean" },
  { country: "Angola", nationality: "Angolan" },
  { country: "Argentina", nationality: "Argentine" },
  { country: "Australia", nationality: "Australian" },
  { country: "Aruba", nationality: "Aruban" },
  { country: "Azerbaijan", nationality: "Azerbaijani" },
  { country: "Bosnia and Herzegovina", nationality: "Bosnian" },
  { country: "Barbados", nationality: "Barbadian" },
  { country: "Bangladesh", nationality: "Bangladeshi" },
  { country: "Bulgaria", nationality: "Bulgarian" },
  { country: "Bahrain", nationality: "Bahraini" },
  { country: "Burundi", nationality: "Burundian" },
  { country: "Bermuda", nationality: "Bermudian" },
  { country: "Brunei Darussalam", nationality: "Bruneian" },
  { country: "Bolivia", nationality: "Bolivian" },
  { country: "Brazil", nationality: "Brazilian" },
  { country: "Bahamas", nationality: "Bahamian" },
  { country: "Bhutan", nationality: "Bhutanese" },
  { country: "Botswana", nationality: "Botswanan" },
  { country: "Belarus", nationality: "Belarusian" },
  { country: "Belize", nationality: "Belizean" },
  { country: "Canada", nationality: "Canadian" },
  { country: "Democratic Republic of the Congo", nationality: "Congolese" },
  { country: "Switzerland", nationality: "Swiss" },
  { country: "Chile", nationality: "Chilean" },
  { country: "China", nationality: "Chinese" },
  { country: "Colombia", nationality: "Colombian" },
  { country: "Costa Rica", nationality: "Costa Rican" },
  { country: "Cuba", nationality: "Cuban" },
  { country: "Cape Verde", nationality: "Cape Verdean" },
  { country: "Czech Republic", nationality: "Czech" },
  { country: "Djibouti", nationality: "Djiboutian" },
  { country: "Denmark", nationality: "Danish" },
  { country: "Dominican Republic", nationality: "Dominican" },
  { country: "Algeria", nationality: "Algerian" },
  { country: "Egypt", nationality: "Egyptian" },
  { country: "Eritrea", nationality: "Eritrean" },
  { country: "Ethiopia", nationality: "Ethiopian" },
  { country: "Eurozone", nationality: "European" },
  { country: "Fiji", nationality: "Fijian" },
  { country: "Falkland Islands", nationality: "Falkland Islander" },
  { country: "Faroe Islands", nationality: "Faroese" },
  { country: "United Kingdom", nationality: "British" },
  { country: "Georgia", nationality: "Georgian" },
  { country: "Guernsey", nationality: "Guernsey" },
  { country: "Ghana", nationality: "Ghanaian" },
  { country: "Gibraltar", nationality: "Gibraltar" },
  { country: "Gambia", nationality: "Gambian" },
  { country: "Guinea", nationality: "Guinean" },
  { country: "Guatemala", nationality: "Guatemalan" },
  { country: "Guyana", nationality: "Guyanese" },
  { country: "Hong Kong", nationality: "Hong Konger" },
  { country: "Honduras", nationality: "Honduran" },
  { country: "Croatia", nationality: "Croatian" },
  { country: "Haiti", nationality: "Haitian" },
  { country: "Hungary", nationality: "Hungarian" },
  { country: "Indonesia", nationality: "Indonesian" },
  { country: "Israel", nationality: "Israeli" },
  { country: "Isle of Man", nationality: "Manx" },
  { country: "India", nationality: "Indian" },
  { country: "Iraq", nationality: "Iraqi" },
  { country: "Iran", nationality: "Iranian" },
  { country: "Iceland", nationality: "Icelander" },
  { country: "Jamaica", nationality: "Jamaican" },
  { country: "Jordan", nationality: "Jordanian" },
  { country: "Japan", nationality: "Japanese" },
  { country: "Kenya", nationality: "Kenyan" },
  { country: "Kyrgyzstan", nationality: "Kyrgyzstani" },
  { country: "Cambodia", nationality: "Cambodian" },
  { country: "Kiribati", nationality: "I-Kiribati" },
  { country: "Comoros", nationality: "Comoran" },
  { country: "South Korea", nationality: "South Korean" },
  { country: "Kuwait", nationality: "Kuwaiti" },
  { country: "Cayman Islands", nationality: "Caymanian" },
  { country: "Kazakhstan", nationality: "Kazakhstani" },
  { country: "Laos", nationality: "Laotian" },
  { country: "Lebanon", nationality: "Lebanese" },
  { country: "Sri Lanka", nationality: "Sri Lankan" },
  { country: "Liberia", nationality: "Liberian" },
  { country: "Lesotho", nationality: "Basotho" },
  { country: "Libya", nationality: "Libyan" },
  { country: "Morocco", nationality: "Moroccan" },
  { country: "Moldova", nationality: "Moldovan" },
  { country: "Madagascar", nationality: "Malagasy" },
  { country: "North Macedonia", nationality: "Macedonian" },
  { country: "Myanmar", nationality: "Burmese" },
  { country: "Mongolia", nationality: "Mongolian" },
  { country: "Macau", nationality: "Macanese" },
  { country: "Mauritania", nationality: "Mauritanian" },
  { country: "Mauritius", nationality: "Mauritian" },
  { country: "Maldives", nationality: "Maldivian" },
  { country: "Malawi", nationality: "Malawian" },
  { country: "Mexico", nationality: "Mexican" },
  { country: "Malaysia", nationality: "Malaysian" },
  { country: "Mozambique", nationality: "Mozambican" },
  { country: "Namibia", nationality: "Namibian" },
  { country: "Nigeria", nationality: "Nigerian" },
  { country: "Nicaragua", nationality: "Nicaraguan" },
  { country: "Norway", nationality: "Norwegian" },
  { country: "Nepal", nationality: "Nepali" },
  { country: "New Zealand", nationality: "New Zealander" },
  { country: "Oman", nationality: "Omani" },
  { country: "Panama", nationality: "Panamanian" },
  { country: "Peru", nationality: "Peruvian" },
  { country: "Papua New Guinea", nationality: "Papua New Guinean" },
  { country: "Philippines", nationality: "Filipino" },
  { country: "Pakistan", nationality: "Pakistani" },
  { country: "Poland", nationality: "Polish" },
  { country: "Paraguay", nationality: "Paraguayan" },
  { country: "Qatar", nationality: "Qatari" },
  { country: "Romania", nationality: "Romanian" },
  { country: "Serbia", nationality: "Serbian" },
  { country: "Russia", nationality: "Russian" },
  { country: "Rwanda", nationality: "Rwandan" },
  { country: "Saudi Arabia", nationality: "Saudi" },
  { country: "Solomon Islands", nationality: "Solomon Islander" },
  { country: "Seychelles", nationality: "Seychellois" },
  { country: "Sudan", nationality: "Sudanese" },
  { country: "Sweden", nationality: "Swedish" },
  { country: "Singapore", nationality: "Singaporean" },
  { country: "Saint Helena", nationality: "Saint Helenian" },
  { country: "Sierra Leone", nationality: "Sierra Leonean" },
  { country: "Somalia", nationality: "Somali" },
  { country: "Suriname", nationality: "Surinamese" },
  { country: "Slovakia", nationality: "Slovak" },
  { country: "Slovenia", nationality: "Slovenian" },
  { country: "Eswatini", nationality: "Swazi" },
  { country: "Syria", nationality: "Syrian" },
  { country: "Chad", nationality: "Chadian" },
  { country: "Togo", nationality: "Togolese" },
  { country: "Thailand", nationality: "Thai" },
  { country: "Tajikistan", nationality: "Tajikistani" },
  { country: "Turkmenistan", nationality: "Turkmen" },
  { country: "Tunisia", nationality: "Tunisian" },
  { country: "Turkey", nationality: "Turkish" },
  { country: "Tanzania", nationality: "Tanzanian" },
  { country: "Uganda", nationality: "Ugandan" },
  { country: "Ukraine", nationality: "Ukrainian" },
  { country: "Uruguay", nationality: "Uruguayan" },
  { country: "United States", nationality: "American" },
  { country: "Uzbekistan", nationality: "Uzbek" },
  { country: "Venezuela", nationality: "Venezuelan" },
  { country: "Vietnam", nationality: "Vietnamese" },
  { country: "Samoa", nationality: "Samoan" },
  { country: "South Africa", nationality: "South African" },
  { country: "Zambia", nationality: "Zambian" },
  { country: "Zimbabwe", nationality: "Zimbabwean" },
];
